image: deepnadig/docker-onos-dev

services:
  - onosproject/onos

test:
  script:
  - sleep 15
  - export ONOS_WEB_USER=onos
  - export ONOS_WEB_PASS=rocks
  - git clone https://git.deepaknadig.com/deepak/OpenSec.git
  - cd OpenSec
  - mvn clean install
  - /root/onos/tools/dev/bin/onos-app onosproject__onos install! target/OpenSec-1.0.2.oar
